### ISSUE TITLE
Crash/freeze during world creation on 1.18.1

### ISSUE THREAD

**Issue by iinterp** [tildejustin/state-output#3]
Creating a world crashes/freezes with state output installed on 1.18.1, the same jar seems to works on 1.18.2 and above.

Tested with:
`state-output-1.1.5+1.18-1.20.4.jar`
`Fabric Loader 0.15.6`
`Java 20.0.1`
With no other mods

[Crash log](https://mclo.gs/E82HEDa)

**Comment by tildejustin** [comment]
all the issues i have with 1.18.1 support usually are fixed by just changing the ranges to 
1.16-1.18.1
1.18.2+
instead of the current
1.16=1.17.1
1.18+
so i'll do that here

**Comment by tildejustin** [comment]
done in https://github.com/tildejustin/state-output/commit/2b3a41e6b080abe429b583b555668bd1b344c147
