### ISSUE TITLE
Doesn't launch on 1.17.1

### ISSUE THREAD

**Issue by iinterp** [tildejustin/state-output#4]
`Mod 'State Output' (state-output) 1.1.5+1.16-1.17.1 requires any version between 1.16 (inclusive) and 1.17.1 (exclusive) of 'Minecraft' (minecraft), but only the wrong version is present: 1.17.1!`

Tested with:
`state-output-1.1.5+1.16-1.17.1.jar`
`Fabric Loader 0.15.6`
`Java 20.0.1`
With no other mods

**Comment by tildejustin** [comment]
https://github.com/tildejustin/state-output/blob/e025ae5a4024c4777eccd392a42db52cae81bb05/1.16-1.17.1/src/main/resources/fabric.mod.json#L19

thank you, that's a typo, it should be >=1.16 <1.18 (or <=1.17.1)
